# Generated by Django 3.2.2 on 2021-05-26 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_auto_20210526_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.category'),
        ),
    ]
